### ISSUE TITLE
Override arity for subscribe to not send `end` callback

### ISSUE THREAD

**Issue by Alotor** [funcool/beicon#10]
Now the subscribe function needs to send the 3 functions (on-value, on-error, on-end) but the `on-end` is seldom needed.

Would be cool to support both arities (3 and 4)

**Comment by niwinz** [comment]
Is that referenced commit is that you are expecting?

**Comment by Alotor** [comment]
Yes :)

**Comment by niwinz** [comment]
Deployed latest snapshot with the change! ;)
