### ISSUE TITLE
combineLatest

### ISSUE THREAD

**Issue by MadMadBeaver** [funcool/beicon#13]
I noticed that there is no wrapping method for **combineLatest**

Is this intentional and do you plan to keep it this way?

**Comment by niwinz** [comment]
No, it is not intentional. Is just becase I have never needed it. PR welcome for adding it ;)

**Comment by MadMadBeaver** [comment]
I use it all the time. RxJS is pretty much useless for me without it :)

OK, I will add it soon

**Comment by niwinz** [comment]
Take care thar `withLatestFrom` is already implemented that is analogous observable member function (instead of static function `combineLatest`) and works in the same way ;)

**Comment by MadMadBeaver** [comment]
Nope, there is a difference (at least in RxJS 4.0 which I use routinely) :)

If you use .combineLatest(a,b), both **a** and **b** could trigger combined signal [a,b]

When using a.withLatestFrom(b), only new **a** could trigger combined signal [a,b], **b** is "passive"

**Comment by niwinz** [comment]
You are right! ;)

**Comment by MadMadBeaver** [comment]
OK, count me as officially stupid but I can't figure out how to run tests for your library.
I've added these to project.clj

:cljsbuild {
              :test-commands
              {"user" ["node" "out/tests.js"]}
              :builds [
              {:main 'beicon.tests.runner
               :output-to "out/tests.js"
               :output-dir "out"
               :target :nodejs
               :optimizations :none
               :pretty-print true
               :language-in  :ecmascript5
               :language-out :ecmascript5
               :verbose true}]}

And receive
Testing beicon.tests.core-tests
Error:  #object[TypeError TypeError: unknown type returned]
Error:  #object[TypeError TypeError: unknown type returned]

What am I doing wrong?

**Comment by niwinz** [comment]
You can build and run tests in the same way as travis does: https://github.com/funcool/beicon/blob/master/.travis.yml#L4

**Comment by MadMadBeaver** [comment]
I tried and it kinda started but It looks like I stumbled in a windows-specific problem :)))
For some weird reason \b in "out\bluebird.js" is treated like a backspace and I somehow end up with path "...beicon\ouluebird.js" caused by cljs.core.load_file("out\bluebird.js") at promesa/core.js

Do they have a facepalm emoji here? :)

**Comment by niwinz** [comment]
LOL

**Comment by niwinz** [comment]
Already implemented in master ;)
