### ISSUE TITLE
with-latest-from doesn't take multiple others.

### ISSUE THREAD

**Issue by luminusian** [funcool/beicon#17]
withLatestFrom in RxJS and RxJava can take multiple others.

https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/withlatestfrom.md

https://github.com/ReactiveX/RxJava/pull/3966

http://reactivex.io/RxJava/javadoc/rx/Observable.html#withLatestFrom(java.lang.Iterable,%20rx.functions.FuncN)

**Comment by niwinz** [comment]
We are not using rxjs 4.x,  the 5.x does not allows multiple observables (http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-withLatestFrom)

I know that the jvm allows it, but it is normalized to one observable for bot impl.
