### ISSUE TITLE
Mathematical and aggregate operators aren't implemented

### ISSUE THREAD

**Issue by luminusian** [funcool/beicon#18]
e.g.
http://reactivex.io/documentation/operators/average.html

**Comment by niwinz** [comment]
PR is welcome ;)

**Comment by jespino** [comment]
This operators are out of the core libraries (rx.aggregates.js in JS) and (rxjava-math in Java) so... it may be out of the scope of the library.

**Comment by niwinz** [comment]
Completely agree with @jespino 

Closing this for the moment.
