### ISSUE TITLE
Adding Observable.fromEvent wrapper

### ISSUE THREAD

**Issue by pepe** [funcool/beicon#29]
Hello, as always thank you for the great libraries I highly appreciate all the work!

I am thinking about replacing this code: https://github.com/pepe/showrum/blob/master/src/cljs/showrum/app.cljs#L19-L22 with reactive stream and for this purpose JS method [Observable.fromEvent()](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#static-method-fromEvent) seems to be appropriate.

I would like to add a wrapper for the method to beicon, but I am not sure if it is not out of the scope of the library.

Please let me know, what you think.

**Comment by niwinz** [comment]
PR is welcome for that :D
