### ISSUE TITLE
JVM concat throws if one observable is a single

### ISSUE THREAD

**Issue by jconti** [funcool/beicon#42]
```
user> (def numbers (rx/from-coll (range 10)))
#'user/numbers
user> (rx/on-value numbers println)
0
1
2
3
4
5
6
7
8
9
#object[beicon.core$wrap_disposable$reify__264 0x79bd924e "beicon.core$wrap_disposable$reify__264@79bd924e"]
user> (rx/on-value (rx/reduce + 0 numbers) println)
45
#object[beicon.core$wrap_disposable$reify__264 0x2de5e902 "beicon.core$wrap_disposable$reify__264@2de5e902"]
user> (rx/on-value (rx/concat numbers (rx/reduce + 0 numbers)) println)
ExceptionInfo Invalid arguments.  clojure.core/ex-info (core.clj:4617)
user> (rx/observable? numbers)
true
user> (rx/observable? (rx/reduce + 0 numbers))
false
user> (rx/single? (rx/reduce + 0 numbers))
true
```

I am running beicon 4.1.0 with Clojure 8.0 and JVM 8.  I plan to send a pull request.

**Comment by jconti** [comment]
#31 Installed support for Flowable.  But it turns out that singles are not observables.  Such is the unfortunate design of RxJava2.  So glad we have beicon to deal with it!

**Comment by niwinz** [comment]
yeah, is clearly a bug

**Comment by niwinz** [comment]
I have pushed the commit https://github.com/funcool/beicon/commit/1fa973628f73e3258135e22fb1de94bcc1505b45 to approach this issue, let me know that you are think about it :D

**Comment by jconti** [comment]
My only comment is I liked the coercions being public.  It made using other parts of rxjava easy and smooth.  I do not see a reason to make them private.  Their functionality is well defined, and matches rxjava nicely.

```
(defn group-by-ob
  [f ob]
  (.groupBy ob (rx/as-function f)))
```

**Comment by niwinz** [comment]
ok, i will make them public again.

**Comment by jconti** [comment]
thanks!

**Comment by jconti** [comment]
I think change does a good job of keeping the current approach intact of not trying to wrap the rx-java library into another set of abstractions which would just add a ton of weight and no value.  It is a hassle when these concrete class leak out, but it is the lesser of the evils IMO.  Thanks for the help!
