### ISSUE TITLE
Coercions are private but useful elsewhere and so should be made public again

### ISSUE THREAD

**Issue by jconti** [funcool/beicon#44]
It is often useful to use the coercions from beicon in user code to adapt normal functions to the types required by RxJava, without having to change beicon itself, or add to the beicon library unnecessarily:

```clojure
(RxJavaPlugins/setErrorHandler (rx/as-consumer global-error-fn))
```

I think they are useful left public, and alter no state or otherwise have a reason to be private.  This, I think, was previously understood, but maybe forgotten:

https://github.com/funcool/beicon/issues/42#issuecomment-385544091

**Comment by niwinz** [comment]
PR welcome ;)
