### ISSUE TITLE
Support for rxjava 3

### ISSUE THREAD

**Issue by Liverm0r** [funcool/beicon#46]
Hey! Are you going to support rxjava 3.x?

**Comment by niwinz** [comment]
yep, i don't start working on it bu it is on the roadmap

**Comment by niwinz** [comment]
On the end I think that for the 6.0.0 I completly remove the clojure part. 
I don't have a good uses cases for rxjava on jvm (having core.async and manifold). Handling backpressure in rxjava and clojure is... not idiomatic. It is not worh the effort of maintaining it.

On the cljs part i using it a lot on many projects and i want to focus on the real use case.

**Comment by jconti** [comment]
I would be sorry to lose support for beicon on the JVM, but I would not be sorry to loose rxjava.  If it was all implemented with `core.async`, that would suit me fine.  The expressiveness of reactive streams is superior to plain `core.async` IMO.  And I think `beicon.core/to-atom` is superior to approaches that define "cells" with "automatic" updates.  Just my 2 cents.  Beicon is one of my favorite libraries.
